version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sas_backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/faces:/app/faces
      - ./backend/encodings.pickle:/app/encodings.pickle
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sas_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped
